---
 - name: ensure dhcpd packages
   package: name=isc-dhcp44-server state=present

 - name: ensure dhcpd config
   template:
    src: dhcpd.conf
    dest: /usr/local/etc/dhcpd.conf
    owner: root
    group: wheel
    mode: '0644'
   notify: restart isc-dhcpd

 - lineinfile:
    path: /etc/rc.conf
    regexp: '^isc-dhcpd_enabled='
    line: 'isc-dhcpd_enabled="YES"'
   notify: restart isc-dhcpd
